name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set Humhub version
      run: |
        HUMHUB_VERSION="$(cat versions.txt)"
        export HUMHUB_VERSION
        echo "HUMHUB_VERSION=$HUMHUB_VERSION" >> "$GITHUB_ENV"
    - name: Build and push docker image
      run: |
        docker build \
          --build-arg HUMHUB_VERSION="${HUMHUB_VERSION}" \
          --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
          --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
          --target runner \
          -t "ghcr.io/${{ github.repository_owner }}/humhub-frankenphp:temp-${{ github.run_id }}-${HUMHUB_VERSION}" \
          .
        docker save "ghcr.io/${{ github.repository_owner }}/humhub-frankenphp:temp-${{ github.run_id }}-${HUMHUB_VERSION}" | gzip > "build-${HUMHUB_VERSION}.tar.gz"
    - name: Upload image archive
      uses: actions/upload-artifact@v7
      with:
        name: build-${{ env.HUMHUB_VERSION }}
        path: build-${{ env.HUMHUB_VERSION }}.tar.gz
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set Humhub version
      run: |
        HUMHUB_VERSION=$(cat versions.txt)
        export HUMHUB_VERSION
        echo "HUMHUB_VERSION=$HUMHUB_VERSION" >> "$GITHUB_ENV"
    - name: Download image archive
      uses: actions/download-artifact@v8
      with:
        name: build-${{ env.HUMHUB_VERSION }}
    - name: Load images
      run: |
        docker load --input "build-${HUMHUB_VERSION}.tar.gz"
    - name: replace image
      run: sed -i "s/docker.io\/jeremyvies\/humhub-frankenphp:latest/ghcr.io\/${{ github.repository_owner }}\/humhub-frankenphp:temp-${{ github.run_id }}-${HUMHUB_VERSION}/g" docker-compose.yml
    - name: Spin up services
      run: docker compose -f docker-compose.yml up -d
    - name: Wait
      run: sleep 60
    - name: Check status
      run: docker ps -a
    - name: Logs
      run: docker compose logs
    - name: Test
      run: curl http://localhost:8080/ -L --fail && curl http://localhost:8080/ -L --fail -s | grep 'Sign in</button>' -q
    - name: Test Email
      run: docker compose exec -T humhub /usr/local/bin/frankenphp php-cli /app/public/protected/yii test/email 'test@example.com' | grep 'Message successfully sent!' -q
    - name: Cleanup
      if: always()
      run: docker compose -f docker-compose.yml down -v
  push_ghcr:
    needs: ["test"]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v7
    - name: Login to registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set Humhub version
      run: |
        HUMHUB_VERSION=$(cat versions.txt)
        export HUMHUB_VERSION
        echo "HUMHUB_VERSION=$HUMHUB_VERSION" >> "$GITHUB_ENV"
    - name: Download image archive
      uses: actions/download-artifact@v8
      with:
        name: build-${{ env.HUMHUB_VERSION }}
    - name: Load, retag and Push images
      run: |
        docker load --input "build-${HUMHUB_VERSION}-frankenphp.tar.gz"
        docker tag "ghcr.io/${{ github.repository_owner }}/humhub-frankenphp:temp-${{ github.run_id }}-${HUMHUB_VERSION}" "ghcr.io/${{ github.repository_owner }}/humhub-frankenphp:${HUMHUB_VERSION}"
        docker push "ghcr.io/${{ github.repository_owner }}/humhub-frankenphp:${HUMHUB_VERSION}"

